### PR TITLE
Scalar color scheme picker

### PR DESCRIPTION
**Pull request by madsendennis**
Adds functionality to change a scalarMesh / scalarTetrahedralMesh's color range. PR #40  will need to be merged before this PR. 
This PR also fixes issue #39 . 

Screen Shot 2019-11-18 at 10 37 33

### CODE REVIEW

**Review by clangguth — APPROVED** [review]
Looks fine to me now. However, feel free to comment or amend my modifications.

Two general comments (not specific to this PR): the header still includes a year for the copyright, I suggest to entirely remove it. And maybe the about box should be revisited concerning the contributors :-)

**Review by marcelluethi — APPROVED** [review]
Thanks, @madsendennis @DanaRahbani @clangguth for the great addition. It looks good to me and can be merged.

**Comment by marcelluethi** [comment]
@madsendennis Please add @noverney as a further co-author of that commit. He has done some part of the code for the panel.

**Comment by madsendennis** [comment]
Thanks for the input @clangguth. It looks much better now. It should now be ready for a merge into the master branch.

**Pull request merged**
