### PR TITLE
avoiding to display child visibility action for empty groups

### PR DESCRIPTION
**Pull request by Ghazi-Bouabene**
Following Mr. Langguth's good suggestion :)

### CODE REVIEW

**Comment by marcelluethi** [comment]
@Ghazi-Bouabene Could that fix go in the 0.13 release?

**Review by Andreas-Forster — APPROVED** [review]
I agree to merge this PR. Thx

**Comment by Ghazi-Bouabene** [comment]
@marcelluethi No. This fix is meant for features that have been merged into develop only today (PRs that have been approved since a while but merged only today). So these features are not in the release branch. Also, given that they have not been tested, I would include them only in the next release.

**Comment by clangguth** [comment]
I haven't tested it, but yeah, looks good to me as well, thanks :)

**Pull request merged**
